import {promises as fs} from "node:fs";
import {spawn} from "node:child_process";
import {RoutingPublisher,connectionRelay} from "./remote/routing.js";
import{createServer}from'node:http';import{randomBytes}from'node:crypto';import{join}from'node:path';import{homedir}from'node:os';import{centerGateway,discoverModels,type ModelServer}from'./remote/center.js';import{readJSON}from'./remote/gateway.js';import{PreviewTunnel}from'./remote/tunnel.js';
const dir=process.env.LOCALBOT_CENTER_DIR??join(homedir(),process.platform==='win32'?'AppData/Local/LocalBotCenter':'.localbot-center');
const csrf=randomBytes(32).toString('hex');let gateway:ReturnType<typeof centerGateway>|undefined;let tunnel=new PreviewTunnel();let publicURL='';let selected:ModelServer|undefined;let starting=false;const routing=new RoutingPublisher();
async function connectServer(server:ModelServer){
 if(starting)throw Error('A connection is already starting.');starting=true;
 try{routing.stop();tunnel.stop();await gateway?.close();selected=server;gateway=centerGateway(join(dir,'devices.json'),selected);const local=await gateway.start();publicURL=process.env.LOCALBOT_PUBLIC_URL??await tunnel.start(local);if(connectionRelay){await routing.start(join(dir,'host-key.json'),connectionRelay,publicURL);publicURL=connectionRelay;}await fs.mkdir(dir,{recursive:true,mode:0o700});await fs.writeFile(join(dir,'server.json'),JSON.stringify(server),{mode:0o600});}
 catch(e){routing.stop();tunnel.stop();await gateway?.close();gateway=undefined;publicURL='';throw e;}
 finally{starting=false;}
}
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LocalBot Center</title><style>
:root{color-scheme:dark light;font:16px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}body{margin:0;background:light-dark(#f4f4f7,#18191c);color:light-dark(#222,#f5f5f7);display:grid;min-height:100vh;place-items:center}main{width:min(600px,calc(100% - 64px));padding:32px;border:1px solid #8883;border-radius:30px;background:light-dark(#fffc,#ffffff08);box-shadow:0 25px 80px #0002;backdrop-filter:blur(20px)}h1{letter-spacing:-1.4px;font-size:36px;margin:10px 0}p{line-height:1.6;color:light-dark(#64646c,#aaaab5)}small{display:block;color:#999;line-height:1.5}button,select,textarea,input{font:inherit;border-radius:12px;padding:13px;border:1px solid #8884;background:light-dark(#fff,#ffffff0b);color:inherit}button{cursor:pointer}button.primary{background:#8f86ff;color:white;border:0}button:disabled{opacity:.4;cursor:default}select,textarea{width:100%;box-sizing:border-box;margin:14px 0}textarea{height:110px;resize:vertical;font:12px ui-monospace,monospace}a:hover{text-decoration:underline}section{margin-top:25px}.row{display:flex;gap:10px;align-items:center}.orb{font-size:36px;color:#c7b6ff}#error{color:#ff9b81}#devices button{float:right;padding:6px 10px}#devices p{min-height:32px}</style>
<main><div class="orb">●</div><h1>LocalBot Center</h1><p>Your models. Connected to LocalBot.<br>Keep Ollama running on this PC. No router setup needed.</p><section><div class="row"><strong>Model server</strong><button id="scan">Refresh</button></div><select id="servers"></select><small id="models">Looking for local models…</small><details><summary>Use another local server</summary><input id="endpoint" placeholder="http://127.0.0.1:1234/v1"><select id="kind"><option value="ollama">Ollama</option><option value="openai">OpenAI compatible</option></select></details><p id="error" role="alert"></p><button class="primary" id="connect">Connect this PC</button></section><section id="pair" hidden><strong>Paste this code in LocalBot → Settings → Connect model PC</strong><textarea id="code" readonly aria-label="Pairing code"></textarea><div class="row"><button id="copy">Copy code</button><button id="new">New code</button></div><p>Works across different networks. This code expires in 10 minutes and can be used once.</p><small>Preview service: keep Center running. Paired devices reconnect when you reopen Center. No shared Wi-Fi is required.</small></section><section id="devices"></section><button id="stop" hidden>Disconnect</button></main>
<script>const token=${JSON.stringify(csrf)};let servers=[];const el=id=>document.getElementById(id);async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-LocalBot-Token':token},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error);return v;}async function action(fn){el('error').textContent='';try{await fn()}catch(e){el('error').textContent=e.message}}async function scan(){servers=await api('/discover');el('servers').replaceChildren(...servers.map((s,i)=>new Option((s.kind==='ollama'?'Ollama':'Compatible server')+' · '+s.models.length+' models',i)));el('connect').disabled=!servers.length&&!el('endpoint').value;showModels();}function showModels(){el('models').textContent=servers[el('servers').value]?.models.join(' · ')||'No models found. Open Ollama and download a model, or enter a local endpoint.';}async function pairing(){const p=await api('/pair',{});el('code').value=p.code;el('pair').hidden=false;}async function devices(){const d=await api('/devices');el('devices').replaceChildren(...d.map(x=>{const p=document.createElement('p');p.textContent=x.name+(x.paired?' · Connected':' · Waiting to pair');const b=document.createElement('button');b.textContent='Revoke';b.onclick=()=>action(async()=>{await api('/revoke',{id:x.id});await devices()});p.append(b);return p;}));}el('scan').onclick=()=>action(scan);el('servers').onchange=showModels;el('endpoint').oninput=()=>el('connect').disabled=false;el('connect').onclick=()=>action(async()=>{el('connect').disabled=true;el('connect').textContent='Connecting…';try{await api('/connect',el('endpoint').value?{endpoint:el('endpoint').value,kind:el('kind').value}:servers[el('servers').value]);await pairing();await devices();el('stop').hidden=false;}finally{el('connect').disabled=false;el('connect').textContent='Connect this PC';}});el('copy').onclick=()=>action(async()=>{await navigator.clipboard.writeText(el('code').value);el('copy').textContent='Copied';});el('new').onclick=()=>action(async()=>{await pairing();await devices()});el('stop').onclick=()=>action(async()=>{await api('/stop',{});el('pair').hidden=true;el('stop').hidden=true;await devices()});action(scan);setInterval(()=>{if(document.hidden)return;api('/status').then(s=>{el('stop').hidden=!s.connected;el('connect').disabled=s.starting;if(s.connected){el('pair').hidden=false;devices().catch(()=>{});}}).catch(()=>{});},5000);</script></html>`;
const ui=createServer(async(req,res)=>{const json=(status:number,data:unknown)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{
 if(!/^(127\.0\.0\.1|localhost)(:\d+)?$/.test(req.headers.host??'')){json(403,{error:'Local access only'});return;}
 if(req.url==='/'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'"});res.end(html);return;}
 if(req.headers['x-localbot-token']!==csrf){json(401,{error:'Reload LocalBot Center to continue.'});return;}
 if(req.url==='/discover'&&req.method==='GET'){json(200,await discoverModels());return;}
 if(req.url==='/status'&&req.method==='GET'){json(200,{connected:!!gateway&&!!publicURL&&!starting,starting});return;}
 if(req.url==='/devices'&&req.method==='GET'){json(200,gateway?.list()??[]);return;}
 if(req.method!=='POST'){json(404,{error:'Not found'});return;}
 const body=await readJSON(req,10000);
 if(req.url==='/connect'){
  await connectServer({kind:body.kind,endpoint:body.endpoint});json(200,{connected:true});return;
 }
 if(req.url==='/pair'){if(!gateway||!publicURL)throw Error('Connect this PC first.');json(200,{code:await gateway.pairing(publicURL,'LocalBot Center',routing.host)});return;}
 if(req.url==='/revoke'){await gateway?.revoke(body.id);json(200,{ok:true});return;}
 if(req.url==='/stop'){await fs.writeFile(join(dir,'server.json'),'null',{mode:0o600});routing.stop();tunnel.stop();await gateway?.close();gateway=undefined;publicURL='';json(200,{ok:true});return;}
 json(404,{error:'Not found'});
 }catch(e){json(400,{error:e instanceof Error?e.message:'Center request failed'});}});
ui.listen(Number(process.env.LOCALBOT_CENTER_PORT??8818),'127.0.0.1',()=>{
 const address='http://127.0.0.1:'+((ui.address() as any).port);console.log('LocalBot Center: '+address);
 if(process.platform==='win32'&&process.env.LOCALBOT_OPEN_CENTER==='1')spawn('cmd.exe',['/c','start','',address],{windowsHide:true,stdio:'ignore'});
 void fs.readFile(join(dir,'server.json'),'utf8').then(async raw=>{const server=JSON.parse(raw);if(server)await connectServer(server);}).catch(()=>{});
});
for(const event of ['SIGINT','SIGTERM'] as const)process.on(event,()=>{routing.stop();tunnel.stop();void gateway?.close();ui.close();});
