// Explicit, bounded integration test. Synthetic arithmetic facts; no user conversation data.
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const root=process.argv[2];
if(!root)throw Error('Pass the workspace data directory.');
const c=JSON.parse(await readFile(join(root,'connection.json'),'utf8'));
const api=async(path,body)=>{const r=await fetch(c.url+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${c.token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d};
const g=await api('/telemetry/gpus');
const options=(await api('/fine-tune/models')).options;
const model=options.find(x=>x.model==='qwen3.8-27b-awq');if(!model)throw Error('Expected Qwen serving model is missing');
const job=await api('/fine-tune/create',{...model,topic:'Verification: elementary arithmetic, checkpoint pause and resume',gpuIds:g.gpus.map(x=>x.id),maxSteps:10,budgetPercent:100,paused:true});
console.log('Verification job',job.id);
for(const split of ['train','eval']){
 const source=await api('/fine-tune/source',{id:job.id,url:`https://example.com/localbot-arithmetic-${split}`,title:`Synthetic arithmetic ${split}`,license:'CC0 — generated mathematical facts',evidence:'Generated by the LocalBot verification harness; answers checked with integer arithmetic. URL is an identifier, not a fetched source.'});
 for(let n=split==='train'?1:21;n<(split==='train'?17:25);n++)await api('/fine-tune/example',{id:job.id,sourceId:source.id??source.sourceId??source,prompt:`What is ${n} plus ${n+1}?`,answer:`${n} plus ${n+1} equals ${2*n+1}.`,split,verification:`Independent integer addition: ${n}+${n+1}=${2*n+1}`});
}
await api('/fine-tune/control',{id:job.id,action:'train'});
let paused=false,resumed=false,last='';
const end=Date.now()+30*60*1000;
while(Date.now()<end){
 const d=await api('/fine-tune/detail?id='+job.id),j=d.job;
 const state=JSON.stringify({status:j.status,step:j.trainingStep,checkpoint:j.checkpoint,reason:j.reason});
 if(state!==last){console.log(state);last=state}
 if(j.status==='waiting')throw Error(j.reason);
 if(!paused&&j.status==='running'&&j.trainingStep>=1){await api('/fine-tune/control',{id:job.id,action:'pause'});paused=true}
 if(paused&&!resumed&&j.status==='paused'){
  if(!j.checkpoint)throw Error('Pause did not save a checkpoint');
  await api('/fine-tune/control',{id:job.id,action:'resume'});resumed=true;
 }
 if(j.status==='completed'){
  if(!resumed)throw Error('Completed without validating resume');
  const resume=d.events.find(e=>e.kind==='training'&&JSON.parse(e.detail).resumedFrom);
  if(!resume)throw Error('Worker did not load the checkpoint');
  await writeFile(join(root,'fine-tune-verification.json'),JSON.stringify({jobId:job.id,completedAt:new Date().toISOString(),paused,resumed,job:j,events:d.events},null,2));
  console.log('VERIFIED_TRAIN_PAUSE_RESUME');process.exit(0);
 }
 await new Promise(r=>setTimeout(r,1000));
}
throw Error('Verification timed out; inspect and pause the recorded job.');
